//
// A C# program that reads two text files and check if a line in first file 
// exists in second file, write it using parallel processing and threads
// Generated by ChatGpt in 02/07/2023
// C# 7 and .Net Framework 4
//
using System;
using System.Collections.Concurrent;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using System.Linq;

class Program
{
    static void Main(string[] args)
    {
        string file1Path = args[0];
        string file2Path = args[1];

        // Read lines
		Console.WriteLine("Reading file {0}", file1Path);
        string[] lines1 = File.ReadAllLines(file1Path);
		Console.WriteLine("Reading file {0}", file2Path);
		string[] lines2 = File.ReadAllLines(file2Path);
		int i = 0;

        // Use parallel processing and threads to check for matching lines
        Parallel.ForEach(lines1, line =>
        {
			if (!lines2.Contains(line))
				Console.WriteLine("Line not found: {0:0000000} => {1}", i + 1, line);
        });

        Console.WriteLine("Done.");
    }
}
