//
// A C# program that reads two text files and check if a line in first file 
// exists in second file, write it using parallel processing and threads
// Generated by ChatGpt in 02/07/2023
// C# 7 and .Net Framework 4
//
using System;
using System.Collections.Concurrent;
using System.IO;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    static void Main(string[] args)
    {
        string file1Path = args[0];
        string file2Path = args[1];

        // Read lines from the first file
        string[] lines1 = File.ReadAllLines(file1Path);

        // Create a blocking collection to store matching lines
        BlockingCollection<string> matchingLines = new BlockingCollection<string>();

        // Use parallel processing and threads to check for matching lines
        Parallel.ForEach(lines1, line =>
        {
            bool foundMatch = false;

            // Read lines from the second file
            using (StreamReader file2 = new StreamReader(file2Path))
            {
                string line2;
                while ((line2 = file2.ReadLine()) != null)
                {
                    if (line == line2)
                    {
                        foundMatch = true;
                        break;
                    }
                }
            }

            // If a matching line is found, add it to the collection
            if (foundMatch)
            {
                matchingLines.Add(line);
            }
        });

        // Print the matching lines
        foreach (var line in matchingLines.GetConsumingEnumerable())
        {
            Console.WriteLine(line);
        }

        // Dispose the blocking collection
        matchingLines.Dispose();
    }
}
